kind: Deployment
apiVersion: apps/v1
metadata:
  name: causas-back-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: causas-back
  template:
    metadata:
      labels:
        app: causas-back
    spec:
      containers:
        - name: causas-back
          image: alejandrogh/causas-back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081    
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: causas-back-service
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 8081
      protocol: TCP
      name: http
      nodePort: 32000
  selector:
    app: causas-back
